# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b75ca75f01e6b0e21202fec6300b13fcc379bd2d431f351fe9785df543ea9a7cd091497c66a49dac6db13b63ceb69c6bc166082c337e52d23d52a9bd30dd278e

test:
  secret_key_base: 916157d1de1bc0d24e5f06719e887aa521ea7ee22bd847d0681b9be80ccfb1176edfc6902c35f45463c6d24c3e5fec0d0a34edbe0f0776b7df5a1cf8de726ce4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
